language: java
jdk:
- openjdk8
addons:
        sonarcloud:
                organization: "francesco1997"
                token:
                       secure: "r3OoEmEzZPxSSfqriSSLaP3kyZUMW0hR02esE92h7hT7kM0GB1OILkSRBUllcmNUj28EqAtO+Wg/1lDCZOuinZ72SlsTjzTwr8FJNj13l0Svr2bTH3YkW+QmY2hl78nxVVLSUu40zeRSFx9en8hWHkdMzlL2TpVfKEgcuFEBdh+Dpdfw1q065D2OjFXtk71GB5DYMEDMqb/6YjIqSf/88MxUCy8sZhLJBau7DToUTnUzu+YkFbRwzChzPli8wd6aI05loMThwXkwylQb1a7opIGxvlmX+9NMqLmp/32vfYEl14lDNIEApbOaz3PLIOXTvqQ/5E3ek8hUWuXcXZ0hhA0HcaL0ki0cMhpVWkihnk43sJIDo5MDIgJnkZVmBCpKo2Hzpg7pdkBDVnOaHhfg3ZZg31JoHov9FF91uqZtGhXXDX6J9T2CwmQmkD3r6d0nSKHDofgoG2PjKj7/gnOOkvB34MDOtubzkaWzitFjZxByshV6hq1F6Xb1JhAW6kn4iq4uLP51FiFP/pVXVXUIYYp8aUBdc8fCiTxqu3dwQoqlhPRks4IQbTpE6y+Za5R3l6KwOhLb22WEqBsEwb3dZ2zCfVwJAhhJFCwFtfAZpEXhotGuL5O3qPK9NI2soDWIeAcyOplQ8I74doUTc/bsKsZKs9A3wY33SaB3UWDzNSI=" 
script: 
        - ant build
        - sonar-scanner
