dist: trusty
language: java
jdk:
- openjdk8
addons:
        sonarcloud:
                organization: "francesco1997"
                token:
                        secure: "EJMKE64z8uYEFlzeAlA/8DEkQxdSfy//Y23FwTO5rg2+EfIy04v7/+phCtDXxguBTTJHgALvOwvIpG0VZOOa/Yyw3j8S/MgR/5FMD5Y2uuAWC03l+NzWKJtYKT+zGDhlPIOfeX4U3E7CKEulACD8Lsy4p4E+Ccn8Qs10H5jVYkXwW+VG+xaf0g7HPQQOAzFKcrcBv9mq86pESwJY1VGB43TmU2B4irAd3aKFGib2DCpdyuvlJCRMA0jOL4dZw7iNJdTUfNga+ULSRJqcM7f8HmO6pWFsBEZ0UobYAZ+0o5At3Sg7Ah+8FsVbtS3oGeujvjaYwsQFtRyRBDAHUzFeKotf2xkWUPRh2f6mXOVDqyHEx6dmjyoO6KSR21sqeVlnB6h2BhiZAhOfKjFT3cK+SXbHnGc4R67odsXhWkLXOEMc1/1OLICB2vtEZFiglNplHf+H3G4a9Q5mS8FyGi6ZmIuVSV8WAgtquypLFJIp9ACsbPKw35YsH2c3oVrJnCehtPLA5lEijnI89djduAYTNd1dtwtwkZSgVJK6H6N9amvOR0pf1bo7U2jXRKlWfFRusYsz8HR/upO/4yDZkFg97/WUyWk6JcYS7+bXHheSwgHd6JxstBBTtTxS20wUc9Kq+keDznyXPNBO/vfInyo4e9JsXhpKNRjVGY04CknL4es="
script: 
        - ant build
        - sonar-scanner
